# emacsclient
# Autogenerated from man page /usr/share/man/man1/emacsclient.1
complete -c emacsclient -s h --description 'print this usage information message and exit SEE ALSO The program is documen…'

