# etags
# Autogenerated from man page /usr/share/man/man1/etags.1
complete -c etags -s d -l defines --description 'Create tag entries for C preprocessor constant definitions and enum constants…'
complete -c etags -s t -l typedefs --description 'Record typedefs in C code as tags.'
complete -c etags -s T -l typedefs-and-c++ --description 'Generate tag entries for typedefs, struct, enum, and union tags, and C++ memb…'

