# locationCLI
# Autogenerated from man page /usr/share/man/man1/locationCLI.1
complete -c locationCLI -s a --description 'Description of -a flag.'
complete -c locationCLI -s b --description 'Description of -b flag \\" Ends the list Pp .'

