# nettop
# Autogenerated from man page /usr/share/man/man1/nettop.1
complete -c nettop -s m --description 'Specify the mode.  By default, nettop will monitor TCP and UDP sockets.'
complete -c nettop -s n --description 'Disable address to name resolution.'
complete -c nettop -s c --description 'Less intensive use of the CPU - draws less often El --------- .'

