# ntpd
# Autogenerated from man page /usr/share/man/man8/ntpd.8
complete -c ntpd -s m --description 'Synchronize using NTP multicast messages on the IP multicast group address 22…'
complete -c ntpd -s v --description '.'
complete -c ntpd -s V --description 'Add a system variable listed by default.'

