# ntptrace
# Autogenerated from man page /usr/share/man/man8/ntptrace.8
complete -c ntptrace -s d --description 'Turn on some debugging output.'
complete -c ntptrace -s n --description 'Turn off the printing of host names; instead, host IP addresses are given.'
complete -c ntptrace -s r --description 'Set the number of retransmission attempts for each host; the default is 5.'
complete -c ntptrace -s t --description 'Set the retransmission timeout (in seconds); the default is 2.'
complete -c ntptrace -s v --description 'Print verbose information about the NTP servers.'

