# rdiff-backup-statistics
# Autogenerated from man page /usr/local/share/man/man1/rdiff-backup-statistics.1
complete -c rdiff-backup-statistics -l begin-time --description 'Do not read statistics files older than R time .'
complete -c rdiff-backup-statistics -l end-time --description 'Like  --begin-time but exclude statistics files later than R time .'
complete -c rdiff-backup-statistics -l minimum-ratio --description 'Print all directories contributing more than the given ratio to the total.'
complete -c rdiff-backup-statistics -l null-separator --description 'Specify that the lines of the file_statistics file are separated by nulls (\\\\…'
complete -c rdiff-backup-statistics -l quiet --description 'Suppress printing of the "Processing statistics from session. " output lines.'

