# rshd
# Autogenerated from man page /usr/share/man/man8/rshd.8
complete -c rshd -s a --description 'This flag is ignored, and is present for compatability purposes.'
complete -c rshd -s D --description 'Sets the TCP_NODELAY socket option, which improves the performance of small b…'
complete -c rshd -s L --description 'Causes all successful accesses to be logged to syslogd 8 as auth.'
complete -c rshd -s l --description 'Do not use the user\'s .'
complete -c rshd -s n --description 'Turn off transport level keepalive messages.'

