# rwhod
# Autogenerated from man page /usr/share/man/man8/rwhod.8
complete -c rwhod -s i --description 'Enable insecure mode, which causes rwhod to ignore the source port on incomin…'
complete -c rwhod -s p --description 'Ignore all POINTOPOINT interfaces.'
complete -c rwhod -s l --description 'Enable listen mode, which causes rwhod to not broadcast any information.'
complete -c rwhod -s m --description 'Cause rwhod to use IP multicast (instead of broadcast) on all interfaces that…'

