# speedtest-cli
# Autogenerated from man page /usr/local/share/man/man1/speedtest-cli.1
complete -c speedtest-cli -s h -l help --description '.'
complete -c speedtest-cli -l bytes --description '.'
complete -c speedtest-cli -l share --description '.'
complete -c speedtest-cli -l simple --description '.'
complete -c speedtest-cli -l csv --description '.'
complete -c speedtest-cli -l csv-delimiter --description '.'
complete -c speedtest-cli -l csv-header --description '.'
complete -c speedtest-cli -l json --description '.'
complete -c speedtest-cli -l list --description '.'
complete -c speedtest-cli -l server --description '.'
complete -c speedtest-cli -l mini --description '.'
complete -c speedtest-cli -l source --description '.'
complete -c speedtest-cli -l timeout --description '.'
complete -c speedtest-cli -l secure --description '.'
complete -c speedtest-cli -l version --description '.'

