# taskgated
# Autogenerated from man page /usr/share/man/man8/taskgated.8
complete -c taskgated -s p --description 'Accepts the old (Tiger) convention that a process with a primary effective gr…'
complete -c taskgated -s s --description 'Allow signed applications marked as "safe" to have free access to task ports,…'
complete -c taskgated -s t --description 'The daemon will quit after that many seconds of inactivity.'
complete -c taskgated -s i --description 'Inject the service port of taskgated into the process with the given pid, rat…'

