# update_dyld_shared_cache
# Autogenerated from man page /usr/share/man/man1/update_dyld_shared_cache.1
complete -c update_dyld_shared_cache -o root --description 'This option specifies the root of an OS installation for which dyld\'s shared …'
complete -c update_dyld_shared_cache -o overlay --description 'This option specifies the root of a sparse directory tree.'
complete -c update_dyld_shared_cache -o arch --description 'By default update_dyld_shared_cache update_dyld_shared_cache generates cache …'
complete -c update_dyld_shared_cache -o force --description 'This option will cause update_dyld_shared_cache update_dyld_shared_cache to r…'
complete -c update_dyld_shared_cache -o debug --description 'This option prints out additional information about the work being done.'
complete -c update_dyld_shared_cache -o sort_by_name --description 'By default update_dyld_shared_cache update_dyld_shared_cache assigns a random…'
complete -c update_dyld_shared_cache -o universal_boot --description 'This option can only be used running on an machine with an Intel processor.'
complete -c update_dyld_shared_cache -o dylib_list --description 'Instead of scanning /var/db/dyld/shared_region_roots/, this option provides a…'
complete -c update_dyld_shared_cache -o verify --description 'Will regenerate a shared cache in-memory that matches the randomization of th…'
complete -c update_dyld_shared_cache -o iPhone --description 'indicates that cache is not for the current Mac OS X, but for rather for an i…'
complete -c update_dyld_shared_cache -o cache_dir --description 'This option specifies the directory in which to create the cache file(s).'

