# visudo
# Autogenerated from man page /usr/share/man/man8/visudo.8
complete -c visudo -l with-env-editor --description 'option or the env_editor Default variable is set in sudoers, visudo will use …'
complete -c visudo -s c --description 'Enable check-only mode.'
complete -c visudo -s q --description 'option was specified.'
complete -c visudo -s f --description '.'
complete -c visudo -s h --description 'The.'
complete -c visudo -s s --description 'Enable strict checking of the sudoers file.'
complete -c visudo -s V --description 'The.'

